# This is a basic workflow to help you get started with Actions

name: Resume-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: "22"

      #Instalar dependencias
      - name: Instalar dependencias
        run: npm install

      #Build de la app
      - name: Build de la app
        run: npm run build:prod

      #Renombrar index para correcto enrutamiento
      - name: Renombrar index para correcto enrutamiento.
        run: mv dist/felix-resume/browser/* dist/felix-resume/ && rm -r dist/felix-resume/browser/ && cp dist/felix-resume/index.html dist/felix-resume/404.html

      #Deploy de la app en GitHub Pages
      - name: Deploy de la app en GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          build_dir: dist/felix-resume/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}